executor:
  build: executor
  ports:
    - "3000:3000"
  links:
    - rethink:db
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - GITHUB_CLIENT=xxx
    - GITHUB_SECRET=yyy
    - JWT_SECRET=zzz

rethink:
  image: rethinkdb:latest
